name = "boutique"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Base de données D1
[[d1_databases]]
binding = "DB"
database_name = "boutique"
database_id = "YOUR_DATABASE_ID"
preview_database_id = "YOUR_PREVIEW_DATABASE_ID"

# Stockage R2 pour les images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "boutique-images"
preview_bucket_name = "boutique-images-preview"

# Variables d'environnement
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-here"
ADMIN_PASSWORD = "admin123"

# Variables d'environnement pour le développement
[env.development]
[env.development.vars]
ENVIRONMENT = "development"

# Limites et configuration
[limits]
cpu_ms = 50