services:
  - type: web
    name: telegram-bot-lanation
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: npm run bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true