name = "boutique-cloudflare"
main = "src/worker/index.js"
compatibility_date = "2024-12-01"
node_compat = true

# Configuration du compte Cloudflare
# account_id = "YOUR_ACCOUNT_ID"

# Routes pour le Worker
routes = [
  { pattern = "boutique.example.com/api/*", zone_name = "example.com" }
]

# Base de données D1
[[d1_databases]]
binding = "DB"
database_name = "boutique-db"
database_id = "YOUR_DATABASE_ID"

# KV Namespaces pour le cache et les sessions
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_CACHE_ID"

[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_KV_SESSIONS_ID"

[[kv_namespaces]]
binding = "CONFIG"
id = "YOUR_KV_CONFIG_ID"

# R2 Bucket pour le stockage d'objets (alternative à Cloudflare Images)
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "boutique-images"

# Variables d'environnement
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "YOUR_JWT_SECRET_HERE"
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_WEBHOOK_SECRET = "YOUR_WEBHOOK_SECRET"

# Configuration pour le développement local
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "boutique-db-dev"
database_id = "local"

# Configuration Cloudflare Images (si vous avez un compte avec Images activé)
[env.production.vars]
CF_ACCOUNT_ID = "YOUR_CLOUDFLARE_ACCOUNT_ID"
CF_IMAGES_TOKEN = "YOUR_CLOUDFLARE_IMAGES_TOKEN"
CF_IMAGES_ACCOUNT_HASH = "YOUR_IMAGES_ACCOUNT_HASH"