name = "boutique-api"
main = "workers/api.ts"
compatibility_date = "2024-01-01"
node_compat = true

[vars]
ADMIN_PASSWORD = "$2a$10$K7L1OJ0TfKBhKlOgGvBK7e.VubRl2jvRwJpHpF8YeWq/ZkJq8N9Oe" # password: admin123

[[d1_databases]]
binding = "DB"
database_name = "boutique-db"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "boutique-images"

[env.production]
vars = { ENVIRONMENT = "production" }